# Generated by Django 5.1.2 on 2025-04-23 20:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_picture_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='primary',
            field=colorfield.fields.ColorField(default='#00A1D8', image_field=None, max_length=25, samples=None),
        ),
    ]
