# Generated by Django 5.1.2 on 2024-10-25 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='valid',
        ),
        migrations.AlterField(
            model_name='band',
            name='associates',
            field=models.ManyToManyField(blank=True, related_name='associated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='bands', to=settings.AUTH_USER_MODEL),
        ),
    ]
