# Generated by Django 5.1.2 on 2024-11-19 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planetplum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='associates',
            field=models.ManyToManyField(blank=True, related_name='associated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='bands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='planetplum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='band',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planetplum.label'),
        ),
        migrations.AddField(
            model_name='show',
            name='bands',
            field=models.ManyToManyField(blank=True, help_text='(Not Required) choose which local bands are playing this show', to='planetplum.band', verbose_name='Local Bands Playing:'),
        ),
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(help_text="what's the name of the show location? **DON'T PUT AN ADDRESS HERE**", on_delete=django.db.models.deletion.RESTRICT, to='planetplum.venue'),
        ),
    ]
