# Generated by Django 5.1.2 on 2024-12-29 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0003_delete_contactrequest_delete_forumpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='picture',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='planetplum.venue'),
        ),
    ]
