# Generated by Django 5.1.2 on 2025-01-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0004_rename_picture_band_image_alter_show_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='approved',
            new_name='valid',
        ),
    ]
