# Generated by Django 5.1.2 on 2025-01-14 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0008_alter_show_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcementimgs/')),
                ('name', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 1, 14, 16, 45, 12, 877116, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='devlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 16, 45, 12, 877116, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 14)),
        ),
    ]
