# Generated by Django 5.1.2 on 2025-01-14 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0009_announcement_alter_devlog_datetime_alter_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devlog',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
