# Generated by Django 5.1.2 on 2025-01-14 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0010_alter_announcement_created_at_alter_devlog_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
