# Generated by Django 5.1.2 on 2025-02-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0011_alter_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='pwyc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
