# Generated by Django 5.1.2 on 2025-02-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0012_show_price_show_pwyc_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
