# Generated by Django 5.1.2 on 2025-02-25 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0013_alter_show_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='banner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CommunityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='community/')),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='planetplum.communitysection')),
            ],
        ),
    ]
