# Generated by Django 5.1.2 on 2025-02-25 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0014_communitysection_announcement_banner_communitylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitylink',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communitylink',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communitylink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/'),
        ),
        migrations.AlterField(
            model_name='communitylink',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='commlink', to='planetplum.communitysection'),
        ),
    ]
