# Generated by Django 5.1.2 on 2025-03-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0015_communitylink_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitylink',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='commlink', to='planetplum.communitysection'),
        ),
    ]
