# Generated by Django 5.1.2 on 2025-04-28 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0016_alter_communitylink_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='associates',
            field=models.ManyToManyField(blank=True, related_name='associated_labels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='band',
            name='associates',
            field=models.ManyToManyField(blank=True, related_name='associated_bands', to=settings.AUTH_USER_MODEL),
        ),
    ]
