# Generated by Django 5.1.2 on 2025-05-07 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0017_label_associates_show_contributor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetplum.band')),
            ],
        ),
    ]
