# Generated by Django 5.1.2 on 2025-05-16 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetplum', '0018_bandlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandlink',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='planetplum.band'),
        ),
    ]
