# Generated by Django 5.1.2 on 2025-04-09 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='channel', to='chat.channelsection'),
        ),
    ]
